# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
end

default_platform(:ios)

platform :ios do
  private_lane :update_version do
    app_store_version = get_app_store_version_number(bundle_id: "KubeControlDashboard")
    plist_version = get_version_number_from_plist(xcodeproj: "KubeControlDashboard.xcodeproj")
    if Gem::Version.new(plist_version.to_f) == Gem::Version.new(app_store_version.to_f)
      UI.message "bumping minor"
      increment_version_number_in_plist(xcodeproj: "KubeControlDashboard.xcodeproj", bump_type: "minor")
    else
      UI.message "bumping patch"
      increment_version_number_in_plist(xcodeproj: "KubeControlDashboard.xcodeproj", bump_type: "patch")
    end
  end

  desc "Run iOS Tests"
  lane :tests do
    run_tests(scheme: "MyAppTests")
  end

  desc "Push a new release build to TestFlight"
  lane :beta4 do
    increment_build_number(xcodeproj: "KubeControlDashboard.xcodeproj")
    match(type: "appstore")
    build_app(scheme: "KubeControlDashboard")
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
    clean_build_artifacts
  end

  desc "Push a new release build to the App Store"
  lane :release do
    increment_build_number(xcodeproj: "KubeControlDashboard.xcodeproj")
    match(type: "appstore")
    build_app(scheme: "KubeControlDashboard")
    upload_to_app_store(
      skip_waiting_for_build_processing: true,
      submit_for_review: true,
      force: true
    )
    clean_build_artifacts
  end
end
